-- NUMERIC FUNCTIONS 

-- ROUND()
SELECT ROUND(12.8), ROUND(12.41,2) FROM DUAL;
-- 8*100 + 1*10 + 2*1
SELECT ROUND(879.41,-3) FROM DUAL;

-- TRUNCATE()  -- IT ONLY EXTRACT values, IT CAN'T ROUND OFF
SELECT TRUNCATE(279.48,1) FROM DUAL;

SELECT TRUNCATE(279.48,1), MOD(21,2), 
21%2 FROM DUAL;

-- POWER()
SELECT TRUNCATE(279.48,1), POW(2,3) FROM DUAL;

-- DATE FUNCTIONS 
SELECT CURDATE() FROM DUAL;
SELECT CURTIME() FROM DUAL;
SELECT NOW() FROM DUAL;
SELECT CURRENT_TIMESTAMP() FROM DUAL;

-- IT SHOWS THE NEXT DAY DATE
SELECT CURDATE(),ADDDATE(CURDATE(),1) FROM DUAL;

-- INTERVAL MONTH AND INTERVAL WEEK DEFINES NEXT MOTNH OR WEEK
SELECT CURDATE(),ADDDATE(CURDATE(),INTERVAL 1 MONTH) FROM DUAL;
SELECT CURDATE(),ADDDATE(CURDATE(),INTERVAL 1 WEEK) FROM DUAL;

-- DATEDIFF
SELECT DATEDIFF(CURDATE(),  ADDDATE(CURDATE(), 
INTERVAL -1 WEEK)) FROM DUAL;

SELECT NOW(), LAST_DAY(NOW()) FROM DUAL;


SELECT DATE_FORMAT(NOW(), '%a' ) FROM DUAL; -- CURRENT DAY btata h %a
SELECT DATE_FORMAT(NOW(), '%b' ) FROM DUAL; -- CURRENT month btata h %b

SELECT DATE_FORMAT(NOW(), 'CURRENT MONTH IS %M') FROM DUAL;

SELECT CURDATE() FROM DUAL; -- YYYY-MM-DD

SELECT CURDATE(), STR_TO_DATE
('17 2025 02', '%d %Y %m' ) FROM DUAL;


