-- Aggregate Function
-- sum(), count(), AVG()

use sakila;

SELECT SUM(AMOUNT) FROM PAYMENT;
SELECT AVG(AMOUNT) FROM PAYMENT;
SELECT COUNT(AMOUNT) FROM PAYMENT;

SELECT AVG(AMOUNT), SUM(AMOUNT)/COUNT(AMOUNT) 
FROM PAYMENT;

-- DISTINCT =>  DUPLICATE VALUES REMOVE KRTA H.
SELECT DISTINCT(AMOUNT) FROM PAYMENT; 

SELECT COUNT(DISTINCT(AMOUNT)), COUNT(AMOUNT) FROM PAYMENT;

SELECT * FROM PAYMENT WHERE AMOUNT = 0.99;
SELECT COUNT(AMOUNT)  FROM PAYMENT WHERE AMOUNT = 0.99;
-- IF THE VALUES ARE NOT PRESENT IN THAT COLUMN IT WILL NOT CALCULATE IT.


-- GROUP BY
-- MULTIPLE SIMILAR VALUES KO EK SATH COLLECT KRTE H 
-- JIS BHI COLUMN PE AAP GROUP BY KRTE VHI COLUMN SELECT KR SKTE H DIRECTLY 
-- SINGLE COULMN SELECT KRTA H TO USKO AGGREGATE FUNCTIONS KE SATH HI USE KR SKTE H.

SELECT AMOUNT FROM PAYMENT GROUP BY AMOUNT;
SELECT AMOUNT, COUNT(AMOUNT) FROM PAYMENT GROUP BY AMOUNT;
SELECT AMOUNT, COUNT(PAYMENT_ID) FROM PAYMENT GROUP BY AMOUNT;

SELECT AMOUNT, COUNT(PAYMENT_ID), SUM(AMOUNT), AVG(AMOUNT)
 FROM PAYMENT GROUP BY AMOUNT;
 
SELECT SUM(AMOUNT) FROM PAYMENT WHERE AMOUNT = 0.99;

SELECT PAYMENT_DATE, MONTH(PAYMENT_DATE) FROM PAYMENT;

SELECT MONTH(PAYMENT_DATE), SUM(AMOUNT) FROM PAYMENT
GROUP BY MONTH(PAYMENT_DATE);


-- GET THE TOTAL AMOUNT AND THE AVERAGE AMOUNT SPEND BY EACH CUSTOMER 
-- GET TTHE TOTAL AMOUNT AND THE MAXIMUM AND MINIMUM AMOUNT FOR EACH STAFF ID 
-- GET THE TOTALK NO OF PAYEMNT DONE BY EACH STAFF
-- GET THE TOTAL AMOUNT THE VERAGE AMOUNT AND THE MINIMUM AMOUNT AND THE MAXIMUM AMOUNT BY EACH CUSTOMER 
-- WHERE THE AMOUNT VALUE SHOULD BE GREATER THAN 2 DOLARS AND THE PAYMENT SHOULD BE GREATER THAN 10.


SELECT CUSTOMER_ID, SUM(AMOUNT), AVG(AMOUNT)
FROM PAYMENT GROUP BY CUSTOMER_ID;

SELECT STAFF_ID, SUM(AMOUNT),MAX(AMOUNT),MIN(AMOUNT) 
FROM PAYMENT GROUP BY STAFF_ID;

SELECT STAFF_ID, COUNT(PAYMENT_ID)
FROM PAYMENT GROUP BY STAFF_ID;


SELECT CUSTOMER_ID, SUM(AMOUNT) ,AVG(AMOUNT) ,MIN(AMOUNT), MAX(AMOUNT)
FROM PAYMENT WHERE AMOUNT > 2
GROUP BY CUSTOMER_ID HAVING COUNT(PAYMENT_ID) > 10;

-- WEHERE AGGRGATE FUNCTION KE SATH NHI LGA SKTE ONLY JO COLUMN PRESENT HO USPE HI LGA SKTE H.
-- HAVING AGGREGATE FUNCTION KE SATH LGA SKTE H .

SELECT AMOUNT , SUM(AMOUNT) FROM PAYMENT 
GROUP BY AMOUNT HAVING SUM(AMOUNT) > 5000;






