USE SAKILA;

-- ORDER BY  => TO ARRANGE IN ORDER
-- ALIAS  => TO GIVE A NICKNAME USING AS

SELECT AMOUNT , AMOUNT * 10 AS NEW FROM PAYMENT;
SELECT AMOUNT , AMOUNT * 10 AS `SELECT` FROM PAYMENT;

SELECT * FROM PAYMENT 
ORDER BY AMOUNT;

SELECT * FROM PAYMENT 
ORDER BY AMOUNT DESC;

SELECT * FROM PAYMENT 
ORDER BY AMOUNT DESC, RENTAL_ID DESC;   -- SUB SORTING


-- FLOW CONTROL FUNCTIONS (CONDITION TRUE/FALSE)
-- 1] CASE
-- 2] IF()
-- 2] IFNULL() 
-- 3] NULLIF()

SELECT AMOUNT,
IF(AMOUNT = 0.99, 'CORRECT', 'INCORRECT')
FROM PAYMENT;

SELECT AMOUNT,        -- NESTED IF 
IF(AMOUNT = 0.99, 'CORRECT', 
   IF(AMOUNT = 2.99, 'YES','INCORRECT'))
FROM PAYMENT;


-- CASE STATEMENT SYNTAX 
---------------------------------------------- 
```
SELECT COL,
  CASE 
      WHEN CONDITION THEN STATEMENT
	  WHEN CONDITION THEN STATEMENT
  END
```
----------------------------------------------
SELECT * FROM PAYMENT;
 SELECT AMOUNT,
 CASE 
   WHEN AMOUNT = 0.99 THEN 'VALUE IS 0.99'
   WHEN AMOUNT = 2.99 THEN 'YES'
   ELSE AMOUNT
END AS COND
FROM PAYMENT;

-- IF THE COUNT OF PAYMENTS DONE FOR EACH AMOUNT IS GREATER THAN 10K
-- THEN PRINT AWE HAVE AMOLUNT GTREATER THAN 10K ELSE LESS THAN 10K

-- IF THE AMOUNT IS GRREATER THAN 1 DOLLAR THEN PRINT AMOUNT IS GREATER THAN 1 DOLLAR
-- IF THE AMOUNT IS GRREATER THAN 2 DOLLAR THEN PRINT AMOUNT IS GREATER THAN 2 DOLLAR
-- IF THE AMOUNT IS GRREATER THAN 3 DOLLAR THEN PRINT AMOUNT IS GREATER THAN 3 DOLLAR
-- OTHERWISE AMOUNT IS LESS THAN 1 DOLLAR 


 SELECT AMOUNT, COUNT(AMOUNT),
    CASE 
        WHEN COUNT(AMOUNT) > 1000 THEN 'WE HAVE AMOUNT GREATER THAN 1K' 
        ELSE 'LESS THAN 10K' 
    END AS PAYMENT_STATUS
FROM PAYMENT
GROUP BY AMOUNT;



SELECT AMOUNT,
    CASE 
        WHEN AMOUNT > 3 THEN 'AMOUNT IS GREATER THAN 3 DOLLAR'
        WHEN AMOUNT > 2 THEN 'AMOUNT IS GREATER THAN 2 DOLLAR'
        WHEN AMOUNT > 1 THEN 'AMOUNT IS GREATER THAN 1 DOLLAR'
        ELSE 'AMOUNT IS LESS THAN 1 DOLLAR'
    END AS AMOUNT_STATUS
FROM PAYMENT;


-- SUBQUERY  => QUERY WITHIN A QUERY 
SELECT * FROM PAYMENT WHERE 
AMOUNT = (SELECT AMOUNT 
           FROM PAYMENT WHERE PAYMENT_ID = 3);


